### PR TITLE
Return null if the pattern of split(), matches(), or replace() is invalid

### LINKED ISSUE #289: Split function invocation can throw an error
**Describe the bug**
If the `split()` function is invoked with an invalid delimiter then the engine throws an exception.

```
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
	at java.util.regex.Pattern.error(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.<init>(Unknown Source) ~[?:?]
	at java.util.regex.Pattern.compile(Unknown Source) ~[?:?]
	at org.camunda.feel.impl.builtin.StringBuiltinFunctions$$anonfun$splitFunction$1.applyOrElse(StringBuiltinFunctions.scala:179) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.impl.builtin.StringBuiltinFunctions$$anonfun$splitFunction$1.applyOrElse(StringBuiltinFunctions.scala:177) ~[feel-engine-1.12.4.jar:1.12.4]
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:241) ~[scala-library-2.13.4.jar:?]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.invokeFunction(FeelInterpreter.scala:775) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.$anonfun$eval$40(FeelInterpreter.scala:189) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.withFunction(FeelInterpreter.scala:742) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.eval(FeelInterpreter.scala:189) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.$anonfun$withCartesianProduct$1(FeelInterpreter.scala:823) ~[feel-engine-1.12.4.jar:1.12.4]
	at scala.collection.immutable.List.map(List.scala:246) ~[scala-library-2.13.4.jar:?]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.withCartesianProduct(FeelInterpreter.scala:823) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.eval(FeelInterpreter.scala:145) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.$anonfun$eval$2(FeelInterpreter.scala:57) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.$anonfun$foldEither$2(FeelInterpreter.scala:234) ~[feel-engine-1.12.4.jar:1.12.4]
	at scala.util.Either$RightProjection.flatMap(Either.scala:757) ~[scala-library-2.13.4.jar:?]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.$anonfun$foldEither$1(FeelInterpreter.scala:234) ~[feel-engine-1.12.4.jar:1.12.4]
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169) ~[scala-library-2.13.4.jar:?]
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165) ~[scala-library-2.13.4.jar:?]
	at scala.collection.immutable.List.foldLeft(List.scala:79) ~[scala-library-2.13.4.jar:?]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.foldEither(FeelInterpreter.scala:233) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.impl.interpreter.FeelInterpreter.eval(FeelInterpreter.scala:59) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.FeelEngine.eval(FeelEngine.scala:200) ~[feel-engine-1.12.4.jar:1.12.4]
	at org.camunda.feel.FeelEngine.$anonfun$eval$2(FeelEngine.scala:196) ~[feel-engine-1.12.4.jar:1.12.4]
	at scala.util.Either.flatMap(Either.scala:352) ~[scala-library-2.13.4.jar:?]
	at org.camunda.feel.FeelEngine.eval(FeelEngine.scala:196) ~[feel-engine-1.12.4.jar:1.12.4]
```

**To Reproduce**
The expression that caused the exception is unknown.

**Expected behavior**
No exception is thrown. Instead, the case is handled and it returns `null`.

Note that no error is returned following the DMN spec :

image

**Environment**
* FEEL engine version: 1.24.4
* Affects: 
  * Camunda BPM: [7.x] 
  * Zeebe broker: 0.26.4 https://github.com/camunda-cloud/zeebe/issues/7347

### PR DESCRIPTION
**Pull request by saig0**
## Description

* return `null` if the pattern is invalid when invoking one of the functions: split(), matches(), or replace()
* following the DMN spec, a function invocation should return `null` instead of propagating an error

## Related issues

closes #289

### CODE REVIEW

File: src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala [hunk 1]
```diff
@@ -95,7 +96,11 @@ object StringBuiltinFunctions {
     params = List("input", "pattern", "replacement"),
     invoke = {
       case List(ValString(input), ValString(pattern), ValString(replacement)) =>
-        ValString(input.replaceAll(pattern, replacement))
+        Try (Pattern.compile(pattern))
+          .map {pattern =>
+            val m = pattern.matcher(input)
+            ValString(m.replaceAll(replacement))
+          }.getOrElse(ValNull)
```
Comment (korthout) [inline src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala]: What happens if you use a context as the pattern? Seems there is only a case for pattern as string. Is that guarded by the builtinFunction?

**Review by korthout — APPROVED** [review]
LGTM 👍

File: src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala (hunk 1 above)
Comment (saig0) [reply src/main/scala/org/camunda/feel/impl/builtin/StringBuiltinFunctions.scala]: Yes. The built-in functions have a guard for illegal arguments: https://github.com/camunda/feel-scala/blob/master/src/main/scala/org/camunda/feel/impl/builtin/BuiltinFunction.scala#L18-L25
