### PR TITLE
fix: number() to return null if the given string is invalid

### LINKED ISSUE #731: number() should return null instead of failing the evaluation
**Describe the bug**
I use the function `number()` to convert a string into a number. If the string is not a number then the evaluation fails.

An evaluation failure is unexpected and it doesn't allow to handle this case.

**To Reproduce**
1. Evaluate the expression 
```
number("x")
```
2. Verify that the evaluation fails

**Expected behavior**
The function should return `null` if the string is not a valid number. 

See the TCK test case [0058-feel-number-function](https://github.com/camunda/dmn-tck/blob/0b613499cd5fe5c49bd99e8c89dc6a13bc425adb/TestCases/compliance-level-3/0058-feel-number-function/0058-feel-number-function.dmn#L166-L174).

**Environment**
* FEEL engine version: `1.17.0`
* Affects: 
  * Camunda Automation Platform 7: [7.x] 
  * Zeebe broker: [0.x] 

Related to https://github.com/camunda/feel-scala/issues/623

### PR DESCRIPTION
**Pull request by saig0**
## Description

Fix the `number()` function to return `null` if the given string is invalid. Before the evaluation failed with an exception. 

## Related issues

closes #731

### CODE REVIEW

File: src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala [hunk 1]
```diff
@@ -170,16 +170,25 @@ class ConversionBuiltinFunctions(valueMapper: ValueMapper) {
     builtinFunction(
       params = List("from"),
       invoke = { case List(ValString(from)) =>
-        ValNumber(from)
+        parseNumber(from)
       }
     )
 
+  private def parseNumber(from: String): Val = {
```
Comment (nicpuppa) [inline src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala:177]: ❓ Is it possible to move this parsing as built in behaviour for `ValNumber` ?

**Review by nicpuppa — APPROVED** [review]
LGTM, I have just a question 🚀

File: src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala (hunk 1 above)
Comment (saig0) [reply src/main/scala/org/camunda/feel/impl/builtin/ConversionBuiltinFunctions.scala:177]: Yes, this would be possible. As part of #65, I plan to remove the implicit conventions from the `package` object and add construction methods to the value types. 

However, this will be part of a bigger refactoring. :telescope:
