### PR TITLE
fix: added fix for negative numbers using modulo

### LINKED ISSUE #152: modulo() function doesn't work for negative numbers
**Describe the bug**
The `modulo()` function produces a wrong result for negative numbers.

**To Reproduce**
Expression: `modulo(10, -4)` returns `2` but should be `-2`.

**Expected behavior**
```
modulo(10, -4) -> -2
modulo(-10, 4) -> 2
modulo(-12, 5) -> -2
modulo(12, -5) -> 2
modulo(-10.1, 4.5) -> 3.4
modulo(10.1, -4.5) -> -3.4
```

**Environment**
* FEEL engine version: 1.11.2

### PR DESCRIPTION
**Pull request by kaaquist**
## Description

* Added a fix for the modulo function to be able to operate with negative numbers.

closes #152

### CODE REVIEW

File: src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala [hunk 1]
```diff
@@ -185,6 +185,16 @@ class BuiltinNumberFunctionsTest
     eval(" modulo(12, 5) ") should be(ValNumber(2))
   }
 
+  it should "return the negative reminder of the division of dividend by divisor" in {
+
+    eval(" modulo(-12, 5) ") should be(ValNumber(-2))
```
Comment (saig0) [inline src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala:190]: Test cases from the spec:

```suggestion
    eval(" modulo(12, -5) ") should be(ValNumber(-3))
    eval(" modulo(-12, -5) ") should be(ValNumber(-2))
    eval(" modulo(10.1, -4.5) ") should be(ValNumber(-3.4))
    eval(" modulo(-10.1, -4.5) ") should be(ValNumber(-1.1))
```

File: src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala [hunk 2]
```diff
@@ -185,6 +185,16 @@ class BuiltinNumberFunctionsTest
...
+  }
+
+  it should "return the positive reminder of the division of dividend by divisor" in {
+
+    eval(" modulo(12, -5) ") should be(ValNumber(2))
```
Comment (saig0) [inline src/test/scala/org/camunda/feel/impl/builtin/BuiltinNumberFunctionTest.scala:195]: Test cases from the spec:

```suggestion
    eval(" modulo(-12, 5) ") should be(ValNumber(3))
    eval(" modulo(-10.1, 4.5) ") should be(ValNumber(3.4))
```

**Review by saig0 — CHANGES_REQUESTED** [review]
@kaaquist thank you for your contribution :fish_cake: 

Unfortunately, the modulo function is not correct yet. Please have a look at the description from the spec:

image

**Review by saig0 — APPROVED** [review]
Looks good. Thanks :tada:
