### PR TITLE
Parse nested path and filter expressions

### LINKED ISSUE #258: complex expressions on lists not parsed correctly since 1.13.0
**Describe the bug**
Since 1.13.0, complex expressions with filters on lists are not correctly parsed by FeelEngine.

**To Reproduce**
1. create following objects
``` kotlin
data class CaseStationFile(
    val id: String,
    val applicantsPersonalData: List<ApplicantsPersonalData> = emptyList(),
)

data class ApplicantsPersonalData(
    val role: String,
    val documents: List<Document> = emptyList(),
)

data class Document(
    val type: String,
    val isValidated: Boolean,
)
```
2. create an instance of CaseStationFile with values below and add it in a Map with key `caseFile`
```kotlin
val caseFile = CaseStationFile("id", listOf(ApplicantsPersonalData("primaryBorrower", listOf(Document("idCard", true)))))
val variables = mapOf("caseFile" to caseFile)
```
3. pass the following expression and the Map to FeelEngine.evalExpression:
``` kotlin
val result = feelEngine.evalExpression("((caseFile.applicantsPersonalData[role=\"primaryBorrower\"])[1].documents[type=\"idCard\"])[1].isValidated", variables)
```

**Expected behavior**
result of evalExpression should be equal to true

It was OK with 1.12.4 and I get following parsing error since 1.13.0:
```
failed to parse expression '((caseFile.applicantsPersonalData[role="primaryBorrower"])[1].documents[type="idCard"])[1].isValidated': Expected (StringIn("<=", ">=", "<", ">", "!=", "=") | "between" | "in" | "and" | "or" | ".."):1:87, found ")[1].isVal"
```

**Environment**
* FEEL engine version: [1.13.1]

### PR DESCRIPTION
**Pull request by saig0**
## Description

* after replacing the parser library in `1.13.0`, some expressions with nested filter and path access can not be parsed anymore (e.g. `([1,2,3,4][item > 2])[1]`, `([{x:{y:1}},{x:{y:2}},{x:{y:3}}]).x[2].y`)
* introduce new parser combinators to parser nested filter and path expressions that follow an expression in brackets
  * instead of using a recursive parsing style as it is currently the case, use a continuation parsing style
  * this style fits better for parsing an expression from left to right and doesn't require limitations to avoid endless recursions
  * since this style seems promising to reduce some limitations of the parser, I plan to roll it out more step-by-step 

## Related issues

closes #258

### CODE REVIEW

File: src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala [hunk 1]
```diff
@@ -118,7 +119,29 @@ object FeelParser {
 
   // 2 a)
   private def textualExpression[_: P]: P[Exp] =
-    P(functionDefinition | forExpression | ifExpression | quantifiedExpression | expression2)
+    P(expressionInBrackets | functionDefinition | forExpression | ifExpression | quantifiedExpression | expression2)
+
+  private def expressionInBrackets[_: P]: P[Exp] =
```
Comment (korthout) [inline src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala:124]: I think the word brackets is generally used specifically for square brackets `[ ]`. Instead, the word parentheses is used for round brackets `( )`. See [bracket](https://en.wikipedia.org/wiki/Bracket).

File: src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala [hunk 2]
```diff
@@ -118,7 +119,29 @@ object FeelParser {
...
+    continuationExpression(base).flatMap(continuation) |
+      End.map(_ => base)
+  )
+
+  private def continuationExpression[_: P](base: Exp): P[Exp] =
+    filterContinuation(base) | pathContinuation(base)
+
+  private def filterContinuation[_: P](base: Exp): P[Exp] =
+    P("[" ~ expression ~ "]")
+      .map(filter => Filter(base, filter))
```
Comment (korthout) [inline src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala:140]: This seems kind of duplicate of `filteredExpression9`. Does this mean the other filterExpressions can be removed or replaced in the future?

**Review by korthout — APPROVED** [review]
I really like the new style. It reads much easier comparing `filterContinuation` to something like `filteredExpression9`.

LGTM already, just a question and a naming suggestion.

File: src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala (hunk 2 above)
Comment (saig0) [reply src/main/scala/org/camunda/feel/impl/parser/FeelParser.scala:140]: Yes. I plan to apply the new style to more places. If this is done then I'll remove the duplications :+1: 
Currently, I want to keep the changes small.
