### PR TITLE
bug(builtin-function): add 'm' parameter support to get entries

### LINKED ISSUE #320: get entries() expects a different argument name
**Describe the bug**
In the DMN 1.3 spec, the function `get entries()` defines the argument: `m` .

But in the engine, the function expects the argument: `context`. 
Background: the function was introduces in the engine before it was introduced in DMN 1.3. 

**To Reproduce**
1. Evaluate the expression 
```
get entries(m:{a: "foo"})
```
2. Verify that the expression evaluates to `null` instead of `"foo"` 

**Expected behavior**
The `get entries()` function can be invoked with the named parameter: `m`.

For backward compatibility, the function should still support the argument: `context`.

**Environment**
* FEEL engine version: `1.13.2`
* Affects: 
  * Camunda BPM: [7.x] 
  * Zeebe broker: [0.x]

### PR DESCRIPTION
**Pull request by P3trur0**
## Description

* Adds the support to `m` argument  name to `get entries` builtin function. 

## Related issues

closes #320

### CODE REVIEW

**Comment by saig0** [comment]
@P3trur0 thank you for your contribution :tada: 
I'll review it soon (~ beginning of next week).

File: src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala [hunk 1]
```diff
@@ -48,6 +48,22 @@ class BuiltinContextFunctionsTest
       Map("key" -> ValString("foo"), "value" -> ValNumber(123)))
   }
 
+  "A get entries function" should "return all entries when invoked with 'm' argument" in {
```
[the remark this answers is not in the document]
Comment (saig0) [reply src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala:51]: :x: We should use the old parameter name in the previous test case. So, we can verify that the previous behavior still works.

File: src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala [hunk 2]
```diff
@@ -243,6 +259,8 @@ class BuiltinContextFunctionsTest
       ValBoolean(true))
     eval(""" context(get entries({a:1,b:2})) = {a:1, b:2} """) should be(
       ValBoolean(true))
+    eval(""" context(get entries(m:{a:1,b:2})) = {a:1, b:2} """) should be(
+      ValBoolean(true))
```
Comment (saig0) [inline src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala:263]: :wrench: We don't need the additional case here. 

This test case verifies the behavior of the `context()` function in combination with `get entries()`. The argument name is not relevant in this test case.

File: src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala [hunk 3]
```diff
@@ -48,6 +48,22 @@ class BuiltinContextFunctionsTest
...
+
+    val items = list.asInstanceOf[ValList].items
+    items should have size 1
+    val context = items(0)
+    context
+      .asInstanceOf[ValContext]
+      .context
+      .variableProvider
+      .getVariables should be(
+      Map("key" -> ValString("foo"), "value" -> ValNumber(123)))
```
Comment (saig0) [inline src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala:64]: :wrench: We could shrink the verification a bit.

```suggestion
    list match {
      case ValList(List(ValContext(context))) =>
        context.variableProvider.getVariables should be(
          Map("key" -> ValString("foo"), "value" -> ValNumber(123)))
      case other => fail(s"Expected list with one context but found '$other'")
    }
```

File: docs/versioned_docs/version-1.14/reference/builtin-functions/feel-built-in-functions-context.md [hunk 4]
```diff
@@ -22,11 +22,11 @@ get value({foo: 123}, "foo")
 Returns the entries of the context as list of key-value-pairs.
 
 * parameters:
-  * `context`: context
+  * `m`: context
 * result: list of context which contains two entries for "key" and "value"
 
 ```js
-get entries({foo: 123})
+get entries(m:{foo: 123})
```
Comment (saig0) [inline docs/versioned_docs/version-1.14/reference/builtin-functions/feel-built-in-functions-context.md:29]: :+1: Thank you for updating the docs!

**Review by saig0 — CHANGES_REQUESTED** [review]
@P3trur0 your PR looks good :+1: 

I've just some minor suggestions. Please have a look.

File: docs/versioned_docs/version-1.14/reference/builtin-functions/feel-built-in-functions-context.md (hunk 4 above)
Comment (P3trur0) [reply docs/versioned_docs/version-1.14/reference/builtin-functions/feel-built-in-functions-context.md:29]: u're welcome: I thought it was better to update them for the sake of completeness 😄

**Comment by P3trur0** [comment]
@saig0 please find PR updated as per your suggestions!

**Comment by saig0** [comment]
@P3trur0 thanks :+1: I merged your PR :tada:
