### PR TITLE
fix: Unary-test behavior with special input variable `?`

### LINKED ISSUE #864: [Bug] Incorrect/inconsistent unary test evaluation when nulls are involved.
**Describe the bug**
There is some inconsistent handling of null when evaluating unary tests. 
I will try to demonstrate below using real examples and screenshots.

1. evaluating `null > 20`
    1. when input value is a random number, this evaluates to false. 
        
image
    2. when input value is null. I would expect the same (since the unary test is not a simple unary test and is not using the input value at all). However, we are getting true. null > 20 => true? This seemed hard to reason about.

image
2. evaluating `? > 20`, and when input value is null. 
image
    However, when i run in expression mode, or using feelin engine, I would see this evaluate to null. If I run it against dsntk, I would get null as the return value as well. 
image

3. Technically speaking DMN spec did not talk about the handling of null when inequality comparison, however based on the guidance over equality comparison, it seems reasonable to suggest that if the two values are not of the same kind, we should expect null as the return value.
image

**To Reproduce**
1.Type in the values as shown in the screenshot in corresponding playground sites. or go to link to spot the inconsistency
https://camunda.github.io/feel-scala/docs/playground/?expression-type=unary-tests&expression=PyA%2BIDIw&context=ewp9&input-value=bnVsbA%3D%3D
https://nikku.github.io/feel-playground/?e=%3F+%3E+20&c=%7B%0A++%22%3F%22%3A+null%0A%7D&t=expression&st=true

**Expected behavior**
This is business critical as it directly impact which rule is determined as a match or not a match when nulls are involved in the evaluation context. It seems like the general consensus is to return null, or consider a rule as not a match for unary tests such as `? > 20`, when ? is null. 

Currently, these null resulting input values are causing unexpected behavior in rule match determination.  I think null will be a more reasonable/spec-compliant return value.
image

**Environment**
* FEEL engine version: [1.x.y]
* Affects: 
  * Camunda Automation Platform 7: [7.x] 
  * Zeebe broker: [0.x] 

**Related**
[SUPPORT-22286](https://jira.camunda.com/browse/SUPPORT-22286)

### PR DESCRIPTION
**Pull request by saig0**
## Description

Fix the behavior of unary-test expressions if the special input variable `?` is used to access the input value. From the following definition, the current behavior is incorrect in case d).

image

**Key idea:**
- Distinguish the case d) from the other cases  
- Limit the access to the special input variable `?` to unary-tests
- Introduce a new error value type to detect the access of `?` and interrupt the evaluation

**Reviewer hint:** 
The first 3 commits are the most relevant. The rest contains a lot of refactoring and may be harder to compare with the original code.

## Related issues

closes #864

### CODE REVIEW

File: src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala [hunk 1]
```diff
@@ -715,25 +724,37 @@ class FeelInterpreter {
...
-              case ValBoolean(true)             => ValBoolean(true)  // the expression is the input value
-              case _ if x == ValBoolean(false)  => ValBoolean(false) // the expression is false
+      inputValue =>
+        eval(expression) match {
+          case _: ValFatalError                       =>
+            eval(expression)(context.add(INPUT_VALUE_SYMBOL -> inputValue)) match {
+              case ValBoolean(true)  => ValBoolean(true)
+              case ValBoolean(false) => ValBoolean(false)
+              case _                 => ValNull
+            }
```
Comment (remcowesterhoud) [inline src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala:701]: ❓ I just want to verify I understand this correct:

1. We try to evaluate the expression with the original input value (null). Somehow this results in a fatal error.
2. We evaluate the expression again setting `?` to the input value (null) in the context. This will evaluate properly to:
    1. True if the expression evaluates to true (eg: `? = null`)
    2. False if the expression evaluates to false (eg `? != null`)
    3. Null if the expression doesn't return a boolean (eg `odd(?)`)


Before the evaluation would result in True because:

1. The fatal error didn't stop the pattern matching early. As a result we'd check equality: `checkEquality(i, x, _ == _, ValBoolean)`
2. `i` and `x` are both null, so they're equal resulting in True.

The entire concept of `?` didn't seem to exist before?

**Review by remcowesterhoud — APPROVED** [review]
Thanks @saig0. I think I understand what's happening but I raised 1 question to be sure. Please have a look 🙂

File: src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala [hunk 2]
```diff
@@ -511,37 +511,112 @@ class InterpreterUnaryTest extends AnyFlatSpec with Matchers with FeelIntegratio
...
+  it should "return true if it evaluates to true when null is assigned to the special variable '?'" in {
+
+    evalUnaryTests(null, "? = null") should be(ValBoolean(true))
+    evalUnaryTests(null, "? = null or odd(?)") should be(ValBoolean(true))
+  }
+
+  it should "return false if it evaluates to false when null is assigned to the special variable '?'" in {
+
+    evalUnaryTests(null, "? != null") should be(ValBoolean(false))
+    evalUnaryTests(null, "? != null and odd(?)") should be(ValBoolean(false))
```
[the remark this answers is not in the document]
Comment (saig0) [reply src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala]: Good point. :+1:

File: src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala [hunk 3]
```diff
@@ -511,37 +511,112 @@ class InterpreterUnaryTest extends AnyFlatSpec with Matchers with FeelIntegratio
...
+
+    evalUnaryTests(5, "null") should be(ValBoolean(false))
+    evalUnaryTests(5, "2 + not_existing") should be(ValBoolean(false))
+    evalUnaryTests(5, "not_existing") should be(ValBoolean(false))
+  }
+
+  it should "return true if it evaluates to true when null is assigned to the special variable '?'" in {
+
+    evalUnaryTests(null, "? = null") should be(ValBoolean(true))
+    evalUnaryTests(null, "? = null or odd(?)") should be(ValBoolean(true))
```
[the remark this answers is not in the document]
Comment (saig0) [reply src/test/scala/org/camunda/feel/impl/interpreter/InterpreterUnaryTest.scala]: True. :+1:

File: src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala (hunk 1 above)
Comment (saig0) [reply src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala:701]: Correct. :100: 

 > The entire concept of ? didn't seem to exist before?

Before, `?` was replaced with the input value. There was no check that the expression must return true. It was not strict enough.

Comment (remcowesterhoud) [reply src/main/scala/org/camunda/feel/impl/interpreter/FeelInterpreter.scala:701]: > Before, ? was replaced with the input value. There was no check that the expression must return true. It was not strict enough.

Thanks for the extra context! All good to merge imo 😄
