### PR TITLE
bug(builtin-function): add 'm' and 'key' parameters support to get value

### LINKED ISSUE #313: get value() expect different argument names
**Describe the bug**
In the DMN 1.3 spec, the function `get value()` defines the arguments: `m` and `key`.

But in the engine, the function expects the arguments: `context` and `key`. 
Background: the function was introduces in the engine before it was introduced in DMN 1.3. 

**To Reproduce**
1. Evaluate the expression 
```
get value(key:"a", m:{a: "foo"})
```
2. Verify that the expression evaluates to `null` instead of `"foo"` 

**Expected behavior**
The `get value()` function can be invoked with the named parameters: `m` and `key`.

For backward compatibility, the function should still support the arguments: `context` and `key`.

**Environment**
* FEEL engine version: `1.13.2`
* Affects: 
  * Camunda BPM: [7.x] 
  * Zeebe broker: [0.x]

### PR DESCRIPTION
**Pull request by P3trur0**
## Description

* Adds `m` and `key` parameters support to `get value`

## Related issues

closes #313

### CODE REVIEW

**Comment by saig0** [comment]
@P3trur0 thank you for your contribution :tada: 
I'll review your PR soon (~ beginning of next week).

File: src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala [hunk 1]
```diff
@@ -54,13 +54,16 @@ class BuiltinContextFunctionsTest
   }
 
   "A get value function" should "return the value" in {
-
     eval(""" get value({foo: 123}, "foo") """) should be(ValNumber(123))
   }
 
-  it should "return null if not contains" in {
+  "A get value function" should "return the value when arguments are named 'm' and 'key'" in {
```
Comment (saig0) [inline src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala:60]: :x: We should group test cases by using it. The test case will be in the same group as the previous test case (i.e. "A get value function").

```suggestion
  it should "return the value when arguments are named 'm' and 'key'" in {
```

Comment (saig0) [reply src/test/scala/org/camunda/feel/impl/builtin/BuiltinContextFunctionsTest.scala:60]: :x: We should use the old parameter name in the previous test case. So, we can verify that the previous behavior still works.

**Review by saig0 — CHANGES_REQUESTED** [review]
@P3trur0 your PR looks good :+1: 

I've just a few minor suggestions. Please have a look.

**Comment by P3trur0** [comment]
@saig0 here you go, suggestions merged.

**Review by saig0 — APPROVED** [review]
@P3trur0 thanks :+1: Your PR is ready to merge :tada:
